sudo: required

services:
  - docker

before_install:
  - docker build -t matiascec/docker-kube_client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run matiascec/docker-kube_client-test npm run test -- --coverage

after_success:
  - docker build -t matiascec/docker-kube-client ./client
  - docker build -t matiascec/docker-kube-nginx ./nginx
  - docker build -t matiascec/docker-kube-server ./server
  - docker build -t matiascec/docker-kube-worker ./worker

  - docker login -u "$REGISTRY_ID" -p "$REGISTRY_PASS"
  - docker push matiascec/docker-kube-client
  - docker push matiascec/docker-kube-nginx
  - docker push matiascec/docker-kube-server
  - docker push matiascec/docker-kube-worker
